image: Visual Studio 2017

build:
  - ps: dotnet --version # to show it is of version 2.0 and that this works fine
  - ps: |  $addAppVeyorTestParameters = @{
            Name = "hello2"
            Framework = 'MSI'
            Filename = "bla.ms"
            Outcome = "failed"
          }
          Add-AppveyorTest $addAppVeyorTestParameters
-
